name: Publish

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Blank (auto), a version (1.4.1), or major/minor/patch
        type: string
      dryRun:
        description: Dry Run?
        type: boolean
        default: false

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  release:
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update NPM for Provence
        run: sudo npm i -g npm@latest

      - name: Bump and Release
        uses: aklinker1/zero-changelog/actions/release@b352bed6e2cad74077baace38bf4eb7fd89883e1 # 0.1.11
        with:
          bump: ${{ inputs.bump }}
          publishCommands: |-
            npm publish
            bunx jsr publish
          dryRun: ${{ inputs.dryRun }}
          dryRunPublishCommands: |-
            npm publish --dry-run
            bunx jsr publish --dry-run --allow-dirty
          githubToken: ${{ secrets.GITHUB_TOKEN }}
